config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
 root "notes#index"
  resources:notes

    devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user, class_name:"User",foreign_key:"user_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :note, class_name: "Note", foreign_key: "note_id"
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.where(user_id: current_user.id.to_i)
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create  

    puts note_params
  
    @note = Note.new(note_params)
    
    
    user=User.find(current_user.id.to_i)
    @note.user_id=user.user_id
    
    p @note
    # new_hash = {id: current_user.id}
    # updated_hash = note_params.merge(new_hash)
    # p "Object #{updated_hash}"
    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created."}
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
        puts @note.errors.full_messages
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated."}
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def note_params
    #   params.fetch(:note, {})
    # end

    def note_params
      params.require(:note).permit(:title,:description)
      # params[:note][:id] = current_user.id
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(user_id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2023 Copyright:
    <a class="text-reset fw-bold" href="https://eldhothampi.com/">eldhothampi.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/layouts/_header.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container-fluid">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
           <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link active'  %>
        </li>
      </ul>
      <!-- Left links -->
    </div>
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Note</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    >
    <script src="https://kit.fontawesome.com/d23bf905b5.js" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render partial: "layouts/header" %>
    <%= yield %>
    </div>
    </div>
    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>
      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container" style="min-height: 42em;">
    <div class="row">
      <div class="col-12 col-md-1">
        <p><label for = "note_title">Title</label>
      </div>
      <div class="col-1 col-md-1">
       <%= text_field 'note', 'title' %></p>
      </div>
    </div>
    <div class="row">
     <div class="col-12 col-md-1">
      <p><label for = "note_description">Description</label>
      </div>
      <div class="col-1 col-md-2">
        <%= text_area 'note', 'description' %></p> 
      </div>     
     </div>   
    <div class="row">
     <div class="col-12 col-md-1">  
     </div>
     <div class="col-12 col-md-1"> 
       <%= form.submit 'Save', class: "btn btn-success"  %>
     </div>
    </div>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>" class="p-2">
  <div class="card " style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title" style="text-align:center"><%= link_to note.title.to_s, note %></h5>
      <p class="card-text"><%= note.description %></p>
    </div>
  <div class="card-footer text-muted"><%= note.updated_at %>
</div>

app/views/notes/edit.html.erb
<h3 style="text-align: center;">Edit note</h3>
<%= link_to "Back", notes_path, class: "btn btn-warning" %>
<%= render "form", note: @note %>

app/views/notes/index.html.erb
<p style="color: green"><%= notice %></p>
<h3 style="text-align: center;">My Notes</h3>
<p style="margin-left:4em">
<%= link_to "Create new note", new_note_path, class: "btn btn-success"%>
</p>
<div id="notes" style="min-height:668px;">
<div class="container">
<div class="row">
  <% @notes.each do |note| %>
    <div class="col-12 col-md-4">
    <div class="card-decks">
    <%= render note %>
    </div>
    </div>
  </div>  
  </div> 
  <% end %>
</div>

app/views/notes/new.html.erb
<h3 style="text-align: center;">Write a note</h3>
<div>
  <%= link_to "Back", notes_path, class: "btn btn-warning" %>
</div>
<%= render "form", note: @note %>
<br>

app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>
<div>
<%= link_to "Back", notes_path, class: "btn btn-warning" %>
<div style="min-height:45em;>
<%= render @note %>
</div>
<div>
 <div class="row">
    <div class="col-2 col-md-1">
    <%= link_to "Edit", edit_note_path(@note), class: "btn btn-primary" %> 
    </div>
    <div class="col-2 col-md-1">
    <%= button_to "Delete", @note, method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
</div>